spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false
server.port=${PORT:8080}
leakcheck.api.key=${LEAKCHECK_KEY:}
app.seed.data=true
